version: '3'
services:
  mongodb:
    container_name: ccc_mongodb
    env_file: .env
    image: "mongo"
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  amp_events:
    build: "./AmpEventImporter"
    container_name: ccc_amp_event_importer
    depends_on: 
      - mongodb
    env_file: .env
    restart: on-failure
  firepower_syslog:
    build: "./FirepowerSyslogImporter"
    container_name: ccc_firepower_syslog
    depends_on:
      - mongodb
    env_file: .env
    ports:
      - "4514:4514/udp"
    restart: on-failure
  stealthwatch_events:
    build: "./StealthwatchEventImporter"
    container_name: ccc_stealthwatch_event_importer
    depends_on: 
      - mongodb
    env_file: .env
    restart: on-failure
  umbrella_events:
    build: "./UmbrellaEventImporter"
    container_name: ccc_umbrella_event_importer
    depends_on: 
      - mongodb
    env_file: .env
    restart: on-failure
  web:
    build: "./Web"
    container_name: ccc_web
    depends_on:
      - mongodb
    env_file: .env
    ports:
      - "5000:5000"
    restart: on-failure
    volumes:
      - ${ISE_PXGRID_CERT_PATH}:/app/pxGrid_cert.pem
      - ${ISE_PXGRID_KEY_PATH}:/app/pxGrid_key.pem
