version: '3'
services:
  mongodb:
    container_name: cc-mongodb
    env_file: .env
    image: "mongo"
    restart: always
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  amp_events:
    build: "./AmpEventImporter"
    container_name: cc-amp-event-importer
    depends_on: 
      - mongodb
    env_file: .env
    restart: on-failure
  api_relay:
    build: "./ApiRelay"
    container_name: cc-api-relay
    depends_on: 
      - mongodb
    environment:
      - ISE_PXGRID_CERT_PATH=/app/pxGrid_cert.pem
      - ISE_PXGRID_KEY_PATH=/app/pxGrid_key.pem
    env_file: .env
    restart: on-failure
    volumes:
      - ${ISE_PXGRID_CERT_PATH}:/app/pxGrid_cert.pem
      - ${ISE_PXGRID_KEY_PATH}:/app/pxGrid_key.pem
  firepower_syslog:
    build: "./FirepowerSyslogImporter"
    container_name: cc-firepower-syslog
    depends_on:
      - mongodb
    env_file: .env
    ports:
      - "4514:4514/udp"
    restart: on-failure
  frontend:
    build: "./Frontend"
    container_name: cc-frontend
    depends_on: 
      - mongodb
    env_file: .env
    restart: on-failure
  proxy:
    build: "./Proxy"
    container_name: cc-proxy
    depends_on:
      - mongodb
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
  stealthwatch_events:
    build: "./StealthwatchEventImporter"
    container_name: cc-stealthwatch-event-importer
    depends_on: 
      - mongodb
    env_file: .env
    restart: on-failure
  umbrella_events:
    build: "./UmbrellaEventImporter"
    container_name: cc-umbrella-event-importer
    depends_on: 
      - mongodb
    env_file: .env
    restart: on-failure
