version: '3'
services:
  mongodb:
    container_name: ccc_mongodb
    env_file: .env
    image: "mongo"
    ports:
      - "27017:27017"
    restart_policy:
      condition: any
  amp_events:
    build: "./AmpEventImporter"
    container_name: ccc_amp_event_importer
    depends_on: 
      - mongodb
    env_file: .env
    restart_policy:
      condition: on-failure
      delay: 30
  firepower_syslog:
    build: "./FirepowerSyslogImporter"
    container_name: ccc_firepower_syslog
    depends_on:
      - mongodb
    env_file: .env
    ports:
      - "4514:4514/udp"
    restart_policy:
      condition: on-failure
