version: '3'
services:
  mongodb:
    container_name: ccc_mongodb
    environment:
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    image: "mongo"
    ports:
      - "27017:27017"
    restart: always
  firepower_syslog:
    build: "./FirepowerSyslogImporter"
    container_name: ccc_firepower_syslog
    depends_on: 
      - mongodb
    environment:
      MONGO_INITDB_ADDRESS: mongodb
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    links:
      - 
    ports:
      - "4514:4514/udp"
    restart: always
