version: '3'
services:
  mongodb:
    container_name: ccc_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE}"
    image: "mongo"
    ports:
      - "27017:27017"
    restart: always
  firepower_syslog:
    build: "./FirepowerSyslogImporter"
    container_name: ccc_firepower_syslog
    ports:
      - "4514/udp:4514/udp"
    restart: always
    volumes:
      - .env:/app/.env
